--United States Of America
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('AL', 'USA', 'Alabama');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('AK', 'USA', 'Alaska');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('AZ', 'USA', 'Arizona');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('AR', 'USA', 'Arkansas');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('CA', 'USA', 'California');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('CO', 'USA', 'Colorado');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('CT', 'USA', 'Connecticut');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('DE', 'USA', 'Delaware');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('FL', 'USA', 'Florida');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('GA', 'USA', 'Georgia');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('HI', 'USA', 'Hawaii');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('ID', 'USA', 'Idaho');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('IL', 'USA', 'Illinois');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('IN', 'USA', 'Indiana');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('IA', 'USA', 'Iowa');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('KS', 'USA', 'Kansas');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('KY', 'USA', 'Kentucky');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('LA', 'USA', 'Louisiana');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('ME', 'USA', 'Maine');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MD', 'USA', 'Maryland');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MA', 'USA', 'Massachusetts');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MI', 'USA', 'Michigan');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MN', 'USA', 'Minnesota');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MS', 'USA', 'Mississippi');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MO', 'USA', 'Missouri');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MT', 'USA', 'Montana');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NE', 'USA', 'Nebraska');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NV', 'USA', 'Nevada');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NH', 'USA', 'New Hampshire');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NJ', 'USA', 'New Jersey');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NM', 'USA', 'New Mexico');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NY', 'USA', 'New York');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NC', 'USA', 'North Carolina');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('ND', 'USA', 'North Dakota');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('OH', 'USA', 'Ohio');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('OK', 'USA', 'Oklahoma');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('OR', 'USA', 'Oregon');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('PA', 'USA', 'Pennsylvania');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('RI', 'USA', 'Rhode Island');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('SC', 'USA', 'South Carolina');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('SD', 'USA', 'South Dakota');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('TN', 'USA', 'Tennessee');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('TX', 'USA', 'Texas');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('UT', 'USA', 'Utah');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('VT', 'USA', 'Vermont');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('VA', 'USA', 'Virginia');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('WA', 'USA', 'Washington');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('WV', 'USA', 'West Virginia');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('WI', 'USA', 'Wisconsin');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('WY', 'USA', 'Wyoming');

--Canada
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('ON', 'CAN', 'Ontario');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('QC', 'CAN', 'Quebec');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NS', 'CAN', 'Nova Scotia');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NB', 'CAN', 'New Brunswick');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('MB', 'CAN', 'Manitoba');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('BC', 'CAN', 'British Columbia');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('PE', 'CAN', 'Prince Edward Island');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('SK', 'CAN', 'Saskatchewan');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('AB', 'CAN', 'Alberta');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NL', 'CAN', 'Newfoundland and Labrador');

--Australia
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('NSW', 'AUS', 'New South Wales');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('QLD', 'AUS', 'Queensland');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('SA', 'AUS', 'South Australia');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('TAS', 'AUS', 'Tasmania');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('VIC', 'AUS', 'Victoria');
INSERT INTO STATE_MASTER (STATE_CODE, COUNTRY_CODE, STATE_NAME) VALUES('WA', 'AUS', 'Western Australia');


